services:
  bun-server:
    env_file:
      - backend/.env
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "9009:9009"
    volumes:
      - ./task-management/server:/app
    networks:
      - app_net
  
  frontend:
    env_file:
      - frontend/.env
    build: 
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "4353:3000"
    volumes:
      - ./task-management/react:/app
    networks:
      - app_net
  caddy:
    image: caddy:2.8.4-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - bun-server
      - frontend
    networks:
      - app_net
networks:
  app_net:
    driver: bridge

# volumes:
#   - ./task-management/react:
#   - ./task-management/server: