
# creating a bsae image
FROM oven/bun:1.1.20-alpine as base

WORKDIR /usr/src/app


# installing dependancy image
FROM base AS install
# for dev environments
# RUN mkdir -p /temp/dev

# COPY package.json bun.lockb /temp/dev/

# RUN cd /temp/dev && bun install --frozen-lockfile


# production install
RUN mkdir -p /temp/prod
COPY package.json bun.lockb /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production


# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image  
FROM base AS prerelease
COPY --from=install /temp/prod/node_modules node_modules
COPY . .
ENV NODE_ENV=production
RUN bun run build


# copy production dependencies and source code into final image
FROM base AS release
COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease /usr/src/app/dist ./dist
COPY --from=prerelease /usr/src/app/package.json .


USER bun
ENTRYPOINT [ "bun", "run", "start" ]